Documentation page
Thomasalex2/Fervent-Ui pull request #2
Opened 2022-02-10 11:56 UTC by Thomasalex2

- Made modifications and tweaks to components in the library (work still needs to be done for further generalizations)
- Added scroll animations to all links and buttons
- Colour scheme is NOT FINAL. So you can mostly ignore that
- Added alerts, badges, buttons, forms, cards, images to the documentation page

2022-02-10 13:49 UTC, deekshithmd commented on styles.css
>      --black-text-color: black;
using color codes will be good

2022-02-10 13:55 UTC, deekshithmd commented on resources/fervent-ui/Components/forms.css
> +    min-height: 50px;
check about using rem here...

2022-02-10 17:00 UTC, AshutoshM29 requested changes

2022-02-10 17:00 UTC, AshutoshM29 commented on resources/fervent-ui/Components/badge.css
> +    bottom: 5px;
Just a small suggestion, try using rem instead of px
rest looks good!!

2022-02-11 16:29 UTC, Thomasalex2 commented on resources/fervent-ui/Components/badge.css
> +    bottom: 5px;
I think I read somewhere that if you are using units less than 10px, its okay to not use rems. But thank you for the suggestion anyway. I'll look it up even more

2022-02-11 16:29 UTC, Thomasalex2 commented on resources/fervent-ui/Components/forms.css
> +    min-height: 50px;
Ahh thanks. Missed that

2022-02-12 16:41 UTC, Thomasalex2 commented
- Suggestions have been incorporated
- The website is feature complete
- Covers all of P0 and some of P1 and P2

2022-02-12 16:41 UTC, merged